#! /bin/sh
### BEGIN INIT INFO
# Provides: dcc
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Current mitter
# Description: This file starts and stops current mitter server
#
### END INIT INFO

case "$1" in
 start)
   /home/mitter/cmservice/daemon-start.sh
   ;;
 stop)
   /home/mitter/cmservice/daemon-stop.sh
   sleep 1
   ;;
 *)
   echo "Usage: mitter {start|stop}" >&2
   exit 3
   ;;
esac
